### PR TITLE
Page watch later

### PR DESCRIPTION
**Pull request by hsnice16**
### This PR will add code for the Design and Functionality of Watch Later 

In this PR, **658 additions and 130 deletions** lines of code
- some files contain only 5 to 6 lines of code
- if you don't like you can avoid reviewing Backend related files

### Please review this PR and give your feedback

---
Watch Later is for Logged In user, so you can use the following credentials
```
email: johndoe@gmail.com
password: johnDoe123
```

OR, you can check its signup functionality, and create a new account.

---

#### [Live URL](https://dekho-video-git-page-watch-later-hsnice16.vercel.app/)
image

### CODE REVIEW

**Review by Dev-AkshatGupta — APPROVED** [review]
Code looks pretty good and The thing is you manage it properly but my small suggestion for you is that sometimes I feel you divide code too much Which I didn't feel right as Sometimes it hinders the dev experience in reading the code. Though else everything was pretty good

**Review by ApurvaSawant11 — APPROVED** [review]
The code looks good to me! UI is also great.

Tried adding to the Watch later list from home page. But did not work. Check  that

**Comment by hsnice16** [comment]
> The code looks good to me! UI is also great.
> 
> Tried adding to the Watch later list from home page. But did not work. Check that

Had you logged in? as the watch later feature is only for logged-in users. I will add `toast` to notify the user, till then please bear with me.

p.s. I tried and it is working for me. Please you try once more too.

**Comment by hsnice16** [comment]
> Code looks pretty good and The thing is you manage it properly but my small suggestion for you is that sometimes I feel you divide code too much Which I didn't feel right as Sometimes it hinders the dev experience in reading the code. Though else everything was pretty good

Thanks for your suggestion, Akshat. Actually, how I divide the code is if something is getting repeated in two or three files, then I extract that thing in a separate file, as the same lines of code are unnecessary increasing the codebase and also file length.

And also, if I will not extract things out then the file length will become too long, and it would be hard to review that file too. I also think it increase the code reusability a lot, as many things I just copied from the last project and it worked perfectly fine without breaking any functionality.

**Comment by ApurvaSawant11** [comment]
> Had you logged in? as the watch later feature is only for logged-in users. I will add `toast` to notify the user, till then please bear with me.
> 
> p.s. I tried and it is working for me. Please you try once more too.

Yes, I had logged in as the watch later page says to login first.

I tried it once again and seems to be working now. Not sure why it did not work previously.

**Comment by hsnice16** [comment]
> > Had you logged in? as the watch later feature is only for logged-in users. I will add `toast` to notify the user, till then please bear with me.
> > p.s. I tried and it is working for me. Please you try once more too.
> 
> Yes, I had logged in as the watch later page says to login first.
> 
> I tried it once again and seems to be working now. Not sure why it did not work previously.

oh! Okay, thanks for checking it again.

**Comment by hsnice16** [comment]
Thank you for reviewing,

**Pull request merged**
